# Generated by Django 4.0.2 on 2022-05-15 18:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AddWork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='title')),
                ('content', models.TextField(verbose_name='content')),
                ('created_date', models.DateField(auto_now=True, verbose_name='Date')),
                ('image', models.FileField(upload_to='#pic', verbose_name='image')),
                ('client', models.CharField(blank=True, max_length=20, verbose_name='client')),
                ('category', models.CharField(blank=True, max_length=30, verbose_name='category')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='author')),
            ],
        ),
    ]
