# Generated by Django 4.0.2 on 2022-05-18 08:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mytest', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_author', models.CharField(max_length=50, verbose_name='author')),
                ('comment_content', models.CharField(max_length=200, verbose_name='content')),
                ('comment_date', models.DateTimeField(auto_now_add=True, null=True, verbose_name='date')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='mytest.addwork', verbose_name='article')),
            ],
        ),
    ]
