# Generated by Django 4.0.2 on 2022-05-16 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='usr_image',
            field=models.ImageField(blank=True, upload_to='', verbose_name='image'),
        ),
    ]
