# Generated by Django 4.0.2 on 2022-05-16 01:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('custom_user', '0002_myuser_usr_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='usr_image',
        ),
    ]
