# Generated by Django 4.0.2 on 2022-05-16 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_user', '0003_remove_myuser_usr_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='usr_password',
            field=models.TextField(blank=True, max_length=30, verbose_name='password'),
        ),
    ]
