# Generated by Django 4.0.2 on 2022-05-16 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_user', '0004_myuser_usr_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='usr_password',
            field=models.CharField(blank=True, max_length=30, verbose_name='password'),
        ),
    ]
